// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5W3zJDKLFIhp5oFokQoLbeA2qsb5xWBo',
    appId: '1:280246137278:web:9f2fa473e15677659909ef',
    messagingSenderId: '280246137278',
    projectId: 'foodapp-af81f',
    authDomain: 'foodapp-af81f.firebaseapp.com',
    databaseURL: 'https://foodapp-af81f-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-af81f.appspot.com',
    measurementId: 'G-B4SWX0PJZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWZuy0B6bw52XpZmWTXNC7gR9USZS0T7g',
    appId: '1:280246137278:android:bc9f3e07ec4bb6ab9909ef',
    messagingSenderId: '280246137278',
    projectId: 'foodapp-af81f',
    databaseURL: 'https://foodapp-af81f-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-af81f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlNluY14r_YE4huVulZy_lly-CGSp0c50',
    appId: '1:280246137278:ios:a5eb84a4399599b99909ef',
    messagingSenderId: '280246137278',
    projectId: 'foodapp-af81f',
    databaseURL: 'https://foodapp-af81f-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-af81f.appspot.com',
    androidClientId: '280246137278-8f6ljff7sqmvbp3fsanlnn6oh39cdubn.apps.googleusercontent.com',
    iosClientId: '280246137278-bqbjgcqnmlmgv00o2i96ldf1qd1h6jvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlNluY14r_YE4huVulZy_lly-CGSp0c50',
    appId: '1:280246137278:ios:a5eb84a4399599b99909ef',
    messagingSenderId: '280246137278',
    projectId: 'foodapp-af81f',
    databaseURL: 'https://foodapp-af81f-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-af81f.appspot.com',
    androidClientId: '280246137278-8f6ljff7sqmvbp3fsanlnn6oh39cdubn.apps.googleusercontent.com',
    iosClientId: '280246137278-bqbjgcqnmlmgv00o2i96ldf1qd1h6jvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBNTgr04uNL2K-i8Fg5MVbbhI0A6PsZHk',
    appId: '1:280246137278:web:cc2171c4584d20739909ef',
    messagingSenderId: '280246137278',
    projectId: 'foodapp-af81f',
    authDomain: 'foodapp-af81f.firebaseapp.com',
    databaseURL: 'https://foodapp-af81f-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-af81f.appspot.com',
    measurementId: 'G-SYP1194GPR',
  );
}


